environment:
  nodejs_version: "20.9.0"

branches:
  only:
    - main

cache: node_modules  

install:
  - npm install  

build: off  

build_script:
  - npm run build   

test_script:
  - npm run lint && npm test 